#-*- coding: utf-8 -*-
from login import *
from welcome import *
from dial import *
from bottom import *
from me import *
from settings import *
from auth import *
from webview import *
from calling import *
from ad import *
from contact_search import *
from multi_call_contact import *
from contact import *
from discovery import *
from random_call import *
from new_contact import *
from contact_dialogbox import *
from contact_detail import *
from contact_free_talk import *
from personality_setting import *
from user_profile import *
from account_balance import *
