#-*- coding: utf-8 -*-
from login import *
from welcome import *
from dial import *
from bottom import *
from me import *
from settings import *
from auth import *
from webview import *
from calling import *
from ad import *
