#-*- coding: utf-8 -*-

## Location info
## pagename_location_name = "xxxxx"
dial_location_title = "com.yx:id/tv_title"
dial_location_top_left_ad = "com.yx:id/rl_dial_left_ad"
dial_location_top_left_new_icon = "com.yx:id/iv_dial_left_ad_new"
dial_location_multi_call = "com.yx:id/right_view_group"
dial_location_search_bar = "com.yx:id/include_search"
dial_location_search_text = "com.yx:id/dial_title_search_text"
dial_location_log_item = "com.yx:id/rlayout_dial_item"
dial_location_log_item_user_avatar = "com.yx:id/circle_iv_dial_icon_user"
dial_location_log_item_system_avatar = "com.yx:id/circle_iv_dial_icon_system"
dial_location_log_item_avatar_tag = "com.yx:id/tv_contact_item_icon_tag"
dial_location_log_item_title = "com.yx:id/tv_dial_title"
dial_location_log_item_uxin_icon = "com.yx:id/iv_dial_yx_tag"
dial_location_log_item_call_way = "com.yx:id/iv_dial_call_way"
dial_location_log_item_subtitle = "com.yx:id/tv_dial_sub_title"
dial_location_log_item_dial_time = "com.yx:id/tv_dial_time"
dial_location_log_item_chat_approach = "com.yx:id/rlayout_dial_detail"
dial_location_log_item_chat_approach_icon = "com.yx:id/iv_dial_detail"
dial_location_keypad = "com.yx:id/include_kaypad"
dial_location_keypad_one = "com.yx:id/keypad_one_layout"
dial_location_keypad_two = "com.yx:id/keypad_two_layout"
dial_location_keypad_three = "com.yx:id/keypad_three_layout"
dial_location_keypad_four = "com.yx:id/keypad_four_layout"
dial_location_keypad_five = "com.yx:id/keypad_five_layout"
dial_location_keypad_six = "com.yx:id/keypad_six_layout"
dial_location_keypad_seven = "com.yx:id/keypad_seven_layout"
dial_location_keypad_eight = "com.yx:id/keypad_eight_layout"
dial_location_keypad_nine = "com.yx:id/keypad_nine_layout"
dial_location_keypad_zero = "com.yx:id/keypad_zero_layout"

# Input cell number page
dial_location_phone_number = "com.yx:id/ed_phone_number"
dial_location_phone_number_location = "com.yx:id/tv_phone_number_location"
dial_location_search_result_list = "com.yx:id/lv_call_record_search"
dial_location_search_result_entry = "com.yx:id/callViewLayout"
dial_location_search_result_entry_icon = "com.yx:id/circle_iv_dial_icon"
dial_location_search_result_entry_name = "com.yx:id/contact_name"
dial_location_search_result_entry_uxin_symbol = "com.yx:id/uxin_symbol"
dial_location_search_result_entry_num = "com.yx:id/contact_phone"
dial_location_search_result_entry_detail = "com.yx:id/enter_detail"


## Verification info
## pagename_verification_name = "xxxxx"
dial_verification_title = u"有信"
dial_verification_search_text = u"搜索"

