#-*- coding: utf-8 -*-

## Location info
## pagename_location_name = "xxxxx"
me_personality_setting_location_back = "com.yx:id/tv_back"
me_personality_setting_location_my = "//android.widget.LinearLayout[@resource-id='com.yx:id/right_view_group']/android.widget.ImageView"
me_personality_setting_calloutshow_location_back = "com.yx:id/tv_back"
me_personality_setting_incoming_location_back = "com.yx:id/tv_back"
me_personality_setting_theme_location_back = "com.yx:id/tv_back"
me_personality_setting_pressmusic_location_back = "com.yx:id/tv_back"
me_personality_setting_starclock_location_back = "com.yx:id/tv_back"
me_personality_setting_my_location_back = "com.yx:id/tv_back"
me_personality_setting_my_location_theme = "com.yx:id/myTheme"
me_personality_setting_my_theme_location_back = "com.yx:id/tv_back"
me_personality_setting_my_location_incoming = "com.yx:id/myIncoming"
me_personality_setting_my_incoming_location_back = "com.yx:id/tv_back"
me_personality_setting_my_location_calloutshow = "com.yx:id/callOutShow"
me_personality_setting_my_calloutshow_location_back = "com.yx:id/tv_back"
me_personality_setting_my_location_pressmusic = "com.yx:id/myPressMusic"
me_personality_setting_my_pressmusic_location_back = "com.yx:id/tv_back"
me_personality_setting_my_location_starclock = "com.yx:id/starClock"
me_personality_setting_my_starclock_location_back = "com.yx:id/tv_back"

## Verification info
## pagename_verification_name = "xxxxx"
me_personality_setting_verification_title = u"个性化设置"
me_personality_setting_calloutshow_verification_title = u"我的去电秀"
me_personality_setting_verification_calloutshow = u"去电秀"
me_personality_setting_verification_incoming = u"来电铃声"
me_personality_setting_incoming_verification_title = u"来电铃声"
me_personality_setting_verification_theme = u"主题"
me_personality_setting_theme_verification_title = u"主题"
me_personality_setting_verification_pressmusic = u"按键音"
me_personality_setting_pressmusic_verification_title = u"按键音"
me_personality_setting_verification_starclock = u"明星闹钟"
me_personality_setting_starclock_verification_title = u"明星闹钟"
me_personality_setting_my_verification_title = u"我的个性化"
me_personality_setting_my_theme_verification_title = u"主题"
me_personality_setting_my_incoming_verification_title = u"来电铃声"
me_personality_setting_my_calloutshow_verification_title = u"我的去电秀"
me_personality_setting_my_pressmusic_verification_title = u"按键音"
me_personality_setting_my_starclock_verification_title = u"明星闹钟"
